### PR TITLE
Allow compiling duperemove against glib prior to 2.36 (lacking g_get_num_processors())

### PR DESCRIPTION
**Pull request by gjtoth**

### CODE REVIEW

**Comment by markfasheh** [comment]
That's fine, but I'm trying to see if we can have a better fallback than just defaulting to 1 for old glib2. If we have to default to 1, then at the least we should print a warning to the user that we failed to accurately get the right number of cpus.

**Comment by gjtoth** [comment]
FWIW, I'd not spend too much effort supporting a library version almost two years old, especially considering that dupermove needs kernel not older than about one year.  Granted, some distros have stable distributions providing recent kernel versions backported but no backported glib (Debian is one) yet I'd rather see development efforts spend elsewhere.  I would in fact be content adding a sentence or two to the man page (maybe to the BUGS section), describing this behavior of duperemove.  What do you think?

**Comment by dickon** [comment]
How about using some other technique for counting CPUs, such as parsing /proc/cpuinfo, with older glibs?

**Comment by clobrother** [comment]
I guess a solution like that is better : https://github.com/clobrother/duperemove/commit/e7a897483493586acca358953fc33e8c3f758f69

**Comment by markfasheh** [comment]
I'm gonna pick up clobrother's fix with his branch so I'll close this for now feel free to reopen if you need to.

**Pull request closed without merging**
