### PR TITLE
removed bloom filter in favor of more efficient use of SQL

### PR DESCRIPTION
**Pull request by lpirl**
As discussed in #69 and as mentioned in the [development tasks](https://github.com/markfasheh/duperemove/wiki/Development-Tasks), I modified `dbfile_load_hashes_bloom` (now `dbfile_load_hashes`) to use the facilities of a database more efficiently.

Thereby, the bloom filter got obsolete when hashing new files and when using an existing database. The corresponding code was removed.

Another implication is that the following functions are now used only by `hashstats`:
* `dbfile_read_all_hashes`
* `dbfile_walk_file_hashes`
* `load_into_hash_tree_cb`

Sadly, the diff looks pretty weird because it looks like in rewrote `dbfile_populate_hashes` into `dbfile_load_hashes` but in fact, `dbfile_populate_hashes` was removed and `dbfile_load_hashes` is the modified version of `dbfile_load_hashes_bloom`.

Regarding the SQL query, I tested the use of `JOIN` in comparison to a query using `IN`.
Because the right side of the `JOIN` is unique, both approaches are equivalent.
`JOIN` turned out to be slightly faster.

In my test case (~24G to scan, a lot of duplicate big files, always creating the hashfile, always hot caches, ~45 sec run time), no significant change in run time could be observed (~2% faster).

To wrap it up, this pull request removes a lot of complexity and comes along with a tiny run time improvement.

### CODE REVIEW

**Comment by markfasheh** [comment]
Btw, give me some time with this one. I'm currently trying to stabilise duperemove for a .10 release after that I can check this out. Mostly I need to get things to a point where I can run my large tests without crashes, *then* I can start profiling the performance difference between two approaches.

If it's mostly a complexity reduction thing then maybe we'll put it in master and leave the bloom filter in .10 for now (in the interest of stabilizing that release sooner). Anyway, I'll get back to this.

**Comment by lpirl** [comment]
Thanks for your reply. Sounds good. I am looking forward for merge/discussion on this.

**Comment by lpirl** [comment]
Hi Marc. Any plans when you could possibly get back to this?
(As long as it does merge easily…)

**Comment by markfasheh** [comment]
Yeah I want to do my 'large test' a few times to get some numbers for us. I still like this patch and I agree that sooner rather than later is the time to merge it (for testing purposes).

**Comment by markfasheh** [comment]
Btw, numbers-wise this is looking pretty good so far.

**Comment by lpirl** [comment]
Nice, thanks – hopefully this will help contributors understand the code more quickly! :)

**Pull request merged**
