### PR TITLE
Print more info for users

### PR DESCRIPTION
**Pull request by Nefelim4ag**

### CODE REVIEW

**Comment by markfasheh** [comment]
Awesome thanks for these patches. Checking the hash vs db in particular has been on my todo list.

I've got them in a branch, I'll cherry pick most of them into master myself. One thing - I'm not sure we need strcimp(). The hash id for each hash will not change unless there's an incompatible change required (in which case we'd treat it as a different hash).

**Comment by Nefelim4ag** [comment]
P.S.
@markfasheh, i've add strcicmp() because db store hash name with capital letter, but in code lowercase letter used.

**Comment by markfasheh** [comment]
Ahh indeed you are correct, we have:

#define		HASH_TYPE_MURMUR3       "Murmur3 "

and then this:

#define DEFAULT_HASH_STR        "murmur3"

and finally we do this when picking a module:

                if (strcasecmp(type, m->name) == 0)
                        break;


Oh bother...

That said, we can still use strcasemp in the dbfile code so I'll just change it to that.

**Comment by Nefelim4ag** [comment]
Thanks

**Pull request closed without merging**
